name: Android CI
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Unit Test
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
      
      - run: npm install
      - run: npm test
      - name: Discord Notification
        if: failure()
        uses: sebastianpopp/discord-action@v1.0
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1051782324452335687/WoUbNdtvovmOK9yfk2flNq1J2GKFuys59mPlL0tbcc_pGFP3aqkV4yMQjHH_o__u-B6q"
        with:
          content: Tests failed on branch ${{ github.ref }}
