name: Test
on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Stacktrace
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: always()

      - name: Send test logs to Discord
        if: always()
        run: |
          generate_post_data() {
          cat <<EOF
          {
          "content": "@everyone Failed Unit!"
          }
          EOF
          }

          curl -X POST -H "Content-Type: application/json" -d "$(generate_post_data)" "{"content":"'\n$(cat ./README.md)\n'"}" "https://discord.com/api/webhooks/1054435033903026277/cooPY5Z9bccgBYiu8XBVoqTQxqgSflBSSJjIzYH9YBSIxwVzJXt4MbfUvc3c5kjJoSst"
